spring:
  activemq:
    broker-url: "failover:(tcp://localhost:61616,tcp://192.168.56.110:61616)?randomize=false"
    packages:
      trusted: "net.brainage.example.model"
      trust-all: true
  datasource:
    url: "jdbc:oracle:thin:@localhost:1521:XE"
    username: "scott"
    password: "tiger"
    hikari:
      data-source-class-name: "oracle.jdbc.pool.OracleDataSource"
      maximum-pool-size: 20
